apiVersion: v1
kind: Service
metadata:
  name: voicebox
  namespace: voicebox
  labels:
    app: voicebox
spec:
  selector:
    app: voicebox
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: metrics
      port: 9464
      targetPort: metrics
