#!/usr/bin/env bash
# Regenerate backend/requirements.lock, the pinned dependency set the Docker
# image installs (Linux x86_64, Python 3.12).  Run it after changing
# backend/requirements.txt or backend/requirements-docker.in.
#
# torch and torchaudio are deliberately left out of the lock: the Dockerfile
# installs the wheels of the chosen PYTORCH_VARIANT first.  uv resolves torch
# from PyPI (the CUDA build) even with the CPU index first, so torch's own
# CUDA runtime packages are filtered out below; nothing else depends on them.
set -euo pipefail
cd "$(dirname "$0")/.."
lock=backend/requirements.lock
uv pip compile backend/requirements.txt backend/requirements-docker.in \
  --python-version 3.12 \
  --python-platform x86_64-manylinux_2_28 \
  --index-url https://download.pytorch.org/whl/cpu \
  --extra-index-url https://pypi.org/simple \
  --index-strategy unsafe-best-match \
  --no-emit-package torch \
  --no-emit-package torchaudio \
  --emit-find-links \
  --annotation-style line \
  --no-header \
  --output-file "$lock"
# Drop the CUDA runtime that only torch's PyPI build pulls in.
tmp=$(mktemp)
grep -v -E '^(nvidia-|cuda-|triton==)' "$lock" > "$tmp"
{
  echo "# Generated by scripts/lock-backend.sh; do not edit by hand."
  echo "# torch/torchaudio and torch's CUDA runtime packages are intentionally absent (see the script)."
  cat "$tmp"
} > "$lock"
rm -f "$tmp"
if grep -q -E '# via .*\b(nvidia-|cuda-|triton)' "$lock"; then
  echo "a package other than torch depends on a filtered CUDA package; review $lock" >&2
  exit 1
fi
echo "wrote $lock ($(grep -c '==' "$lock") pins)"
